## Importing libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sn

## Importing the dataset

In [2]:
df=pd.read_csv('Iris.csv')

In [ ]:
df.describe()

##Label Encoder

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Species'] = le.fit_transform(df['Species'])
df.head()

In [ ]:
print(df["Species"])

##Spliting data into Features and Target variable

In [4]:
X= df.iloc[:,:-1].values
y= df.iloc[:,-1].values

In [ ]:
print(X)

In [ ]:
print(y)

##Data Visualization

In [ ]:
sn.pairplot(df,hue="Species")

## Spliting the DataFrame in Train and Test set

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 30, random_state =42)

##Traning the model using Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
model= LogisticRegression()
model.fit(X_train, y_train)

##Predicting the Model on Test set

In [ ]:
pred= model.predict(X_test)
print(np.concatenate((pred.reshape(len(pred),1), y_test.reshape(len(y_test),1)),1))

##Confusion Matrix and Accuracy Score

In [12]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm= confusion_matrix(y_test, pred)
print(cm)
accuracy_score(y_test, pred)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


1.0

##Predicting on a Single flower

In [14]:
print(model.predict([[100,5.7,2.8,4.1,1.3]]))

[1]


##Summary

**An Iris flower classification model was developed using a dataset retrieved from 'Iris.csv', consisting of features related to sepal and petal dimensions (Sepal Length, Sepal Width, Petal Length, and Petal Width) along with the species label ('Species'). The dataset was preprocessed by encoding the categorical species labels using LabelEncoder. A pair plot was created using Seaborn to visualize the relationships between features, distinguished by species. The dataset was split into training and testing sets using a 30-sample test size and a random state of 42. A Logistic Regression model was employed to classify the Iris species based on the provided features. The model was trained on the training data and then used to predict the species labels for the test set. The predictions were compared with the actual test labels using a confusion matrix and evaluated for accuracy, yielding the accuracy score. Lastly, a prediction was made for a new set of feature values ([100, 5.7, 2.8, 4.1, 1.3]) to determine the probable species of an Iris flower based on the trained Logistic Regression model.**